version: '3.5'
services:
  local:
    container_name: local
    build: .
    stdin_open: true
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8082:8082"
      - "5005:5005"
    environment:
      cluster_env: 'LOCAL'
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: developer
      DB_PASSWORD: mysecretpassword
    working_dir: /app
    command: bash -c 'bash'
    networks:
      - foodnetwork
networks:
  foodnetwork:
      external: true
      name: food_inc_network

volumes:
  gradle_cache: